### ISSUE TITLE
No compatibility with newer version of SDK

### ISSUE THREAD

**Issue by Oleygen** [kohtenko/KOActivityIndicator#2]
You have this code:

   private var positionKeyTimes: [AnyObject] {
        get{
            switch style{
            case .SpinInEnd:
                return [0, 0.2, 0.5, 0.7, 1]
            case .SpinInMove:
                return [0, 0.2, 0.5, 0.7, 1]
            case .NoSpin:
                return [0, 0.5, 1]
            default:
                return []
            }
        }
    }

```
private var rotationKeyTimes: [AnyObject] {
    get{
        switch style{
        case .SpinInEnd:
            return [0.0, 0.3, 0.5, 0.5, 1]
        case .SpinInMove:
            return [0.0, 0.25, 0.5, 1]
        case .NoSpin:
            return []
        default:
            return []
        }
    }
}
```

and crush on this lines:
        animation1.keyTimes = positionKeyTimes
        animation2.keyTimes = rotationKeyTimes

caused of type mismatching. You have to change 
   private var positionKeyTimes: [AnyObject] { ->    private var positionKeyTimes: [NSNumber] {
    private var rotationKeyTimes: [AnyObject] { ->     private var rotationKeyTimes: [NSNumber] {

P.S. m.b. I have to fork this one with myself but I'm newbie in git and afraid to break smt
P.P.S. sry for my english :-)

**Comment by kohtenko** [comment]
Should be sold in latest release (0.0.2). 
Sorry for long response
